version: '3'
services:
  mysql:
    image: mysql:8.4
    hostname: mysql
    volumes:
      - './mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
      - './mysql/data:/var/lib/mysql' #PUT DUMP.SQL HERE
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST= "0.0.0.0"
      - MYSQL_DATABASE=database
      - MYSQL_USER=maksarovd
      - MYSQL_PASSWORD=Maksarovd1989
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
