version: '3'
services:
  mysql:
    image: mysql:5.7.37
    restart: "no"
    hostname: mysql
    volumes:
      - './mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
      - './mysql:/home' #PUT DUMP.SQL HERE
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST= "0.0.0.0"
      - MYSQL_DATABASE=database
      - MYSQL_USER=maksarovd
      - MYSQL_PASSWORD=1
